In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1={
    "name":["kanav","ashna","moksh"],
    "age":[18,14,18],
    "hobby":["cricket","singing","sleeping"]
}

In [3]:
data=pd.DataFrame(dict1)

In [4]:
data

    name  age     hobby
0  kanav   18   cricket
1  ashna   14   singing
2  moksh   18  sleeping

In [5]:
data.head()

    name  age     hobby
0  kanav   18   cricket
1  ashna   14   singing
2  moksh   18  sleeping

In [6]:
data.tail(1)

    name  age     hobby
2  moksh   18  sleeping

In [7]:
data.describe()

             age
count   3.000000
mean   16.666667
std     2.309401
min    14.000000
25%    16.000000
50%    18.000000
75%    18.000000
max    18.000000

In [8]:
data.to_csv('person.csv')

In [9]:
x=pd.read_csv('person.csv')

In [10]:
x

   Unnamed: 0   name  age     hobby
0           0  kanav   18   cricket
1           1  ashna   14   singing
2           2  moksh   18  sleeping

In [11]:
x['age']

0    18
1    14
2    18
Name: age, dtype: int64

In [12]:
x.index=['first','second','third']

In [13]:
x

        Unnamed: 0   name  age     hobby
first            0  kanav   18   cricket
second           1  ashna   14   singing
third            2  moksh   18  sleeping

In [14]:
ser=pd.Series(np.random.rand(23))

In [15]:
ser

0     0.861997
1     0.288299
2     0.284522
3     0.285790
4     0.240075
5     0.119060
6     0.039346
7     0.142997
8     0.982039
9     0.955858
10    0.257345
11    0.143274
12    0.937352
13    0.867550
14    0.647187
15    0.930359
16    0.211812
17    0.235267
18    0.205939
19    0.486593
20    0.318980
21    0.866997
22    0.824754
dtype: float64

In [16]:
newdata=pd.DataFrame(np.random.rand(45,5))

In [17]:
newdata

           0         1         2         3         4
0   0.699851  0.902919  0.206073  0.554898  0.151099
1   0.684678  0.500808  0.533985  0.449384  0.737692
2   0.219925  0.486893  0.821266  0.656441  0.143207
3   0.268679  0.184527  0.234566  0.572500  0.081354
4   0.602703  0.092030  0.484072  0.553153  0.056897
5   0.159715  0.852080  0.821361  0.284793  0.916859
6   0.067496  0.586100  0.557994  0.434372  0.150084
7   0.653994  0.929904  0.931783  0.393055  0.207937
8   0.224971  0.430545  0.843217  0.796591  0.935713
9   0.065126  0.973478  0.131529  0.718802  0.744131
10  0.146884  0.890580  0.389648  0.440771  0.094700
11  0.946456  0.347649  0.873119  0.468704  0.224748
12  0.873640  0.711396  0.002291  0.407651  0.042966
13  0.710629  0.522614  0.502739  0.965866  0.779095
14  0.565746  0.391658  0.085734  0.512756  0.693110
15  0.238048  0.325942  0.817357  0.760907  0.518661
16  0.209784  0.504297  0.861570  0.152021  0.923682
17  0.421532  0.146324  0.808740  0.952656  0.896506
18  0.044969  0.994673  0.272777  0.050108  0.088981
19  0.705640  0.389937  0.164520  0.870851  0.307066
20  0.868214  0.980651  0.452114  0.094781  0.174555
21  0.698260  0.720160  0.644696  0.188355  0.130361
22  0.462878  0.032441  0.156970  0.923028  0.384788
23  0.654036  0.922637  0.542051  0.895928  0.051350
24  0.065193  0.052311  0.068743  0.746873  0.443335
25  0.662451  0.686360  0.418597  0.048628  0.898074
26  0.790025  0.113649  0.164265  0.887840  0.576013
27  0.608702  0.709287  0.816681  0.882616  0.018045
28  0.338291  0.953841  0.764361  0.448757  0.258737
29  0.592189  0.822408  0.082231  0.582628  0.748582
30  0.438939  0.856968  0.535160  0.129146  0.039174
31  0.849944  0.879199  0.091932  0.527329  0.326256
32  0.694666  0.292216  0.681798  0.101577  0.923072
33  0.945329  0.976046  0.046019  0.158440  0.453744
34  0.667737  0.639761  0.844519  0.466747  0.102956
35  0.696356  0.060102  0.403648  0.171275  0.982808
36  0.131567  0.199459  0.754362  0.657594  0.149679
37  0.648021  0.560635  0.646443  0.368406  0.176753
38  0.717238  0.919358  0.990939  0.248833  0.947207
39  0.538199  0.735052  0.566461  0.756818  0.092634
40  0.695765  0.406977  0.335490  0.926116  0.987676
41  0.877890  0.653603  0.386444  0.997482  0.458876
42  0.561140  0.986398  0.392136  0.104247  0.932421
43  0.191855  0.179711  0.854788  0.666266  0.677819
44  0.251519  0.987706  0.085187  0.810667  0.463968

In [18]:
newdata.describe()

               0          1          2          3          4
count  45.000000  45.000000  45.000000  45.000000  45.000000
mean    0.514597   0.588695   0.490453   0.528592   0.446519
std     0.271440   0.315072   0.296740   0.291365   0.341473
min     0.044969   0.032441   0.002291   0.048628   0.018045
25%     0.238048   0.347649   0.206073   0.284793   0.143207
50%     0.602703   0.639761   0.502739   0.527329   0.384788
75%     0.698260   0.890580   0.808740   0.760907   0.748582
max     0.946456   0.994673   0.990939   0.997482   0.987676

In [19]:
newdata.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [20]:
newdata[1][2]="kanav"

In [21]:
newdata

           0         1         2         3         4
0   0.699851  0.902919  0.206073  0.554898  0.151099
1   0.684678  0.500808  0.533985  0.449384  0.737692
2   0.219925     kanav  0.821266  0.656441  0.143207
3   0.268679  0.184527  0.234566  0.572500  0.081354
4   0.602703   0.09203  0.484072  0.553153  0.056897
5   0.159715   0.85208  0.821361  0.284793  0.916859
6   0.067496    0.5861  0.557994  0.434372  0.150084
7   0.653994  0.929904  0.931783  0.393055  0.207937
8   0.224971  0.430545  0.843217  0.796591  0.935713
9   0.065126  0.973478  0.131529  0.718802  0.744131
10  0.146884   0.89058  0.389648  0.440771  0.094700
11  0.946456  0.347649  0.873119  0.468704  0.224748
12  0.873640  0.711396  0.002291  0.407651  0.042966
13  0.710629  0.522614  0.502739  0.965866  0.779095
14  0.565746  0.391658  0.085734  0.512756  0.693110
15  0.238048  0.325942  0.817357  0.760907  0.518661
16  0.209784  0.504297  0.861570  0.152021  0.923682
17  0.421532  0.146324  0.808740  0.952656  0.896506
18  0.044969  0.994673  0.272777  0.050108  0.088981
19  0.705640  0.389937  0.164520  0.870851  0.307066
20  0.868214  0.980651  0.452114  0.094781  0.174555
21  0.698260   0.72016  0.644696  0.188355  0.130361
22  0.462878  0.032441  0.156970  0.923028  0.384788
23  0.654036  0.922637  0.542051  0.895928  0.051350
24  0.065193  0.052311  0.068743  0.746873  0.443335
25  0.662451   0.68636  0.418597  0.048628  0.898074
26  0.790025  0.113649  0.164265  0.887840  0.576013
27  0.608702  0.709287  0.816681  0.882616  0.018045
28  0.338291  0.953841  0.764361  0.448757  0.258737
29  0.592189  0.822408  0.082231  0.582628  0.748582
30  0.438939  0.856968  0.535160  0.129146  0.039174
31  0.849944  0.879199  0.091932  0.527329  0.326256
32  0.694666  0.292216  0.681798  0.101577  0.923072
33  0.945329  0.976046  0.046019  0.158440  0.453744
34  0.667737  0.639761  0.844519  0.466747  0.102956
35  0.696356  0.060102  0.403648  0.171275  0.982808
36  0.131567  0.199459  0.754362  0.657594  0.149679
37  0.648021  0.560635  0.646443  0.368406  0.176753
38  0.717238  0.919358  0.990939  0.248833  0.947207
39  0.538199  0.735052  0.566461  0.756818  0.092634
40  0.695765  0.406977  0.335490  0.926116  0.987676
41  0.877890  0.653603  0.386444  0.997482  0.458876
42  0.561140  0.986398  0.392136  0.104247  0.932421
43  0.191855  0.179711  0.854788  0.666266  0.677819
44  0.251519  0.987706  0.085187  0.810667  0.463968

In [22]:
newdata.to_numpy()

array([[0.6998511385554222, 0.902919441662445, 0.20607282067017352,
        0.5548982693863784, 0.1510987024014112],
       [0.6846783107635002, 0.5008076745217478, 0.5339848519167673,
        0.4493842997497358, 0.7376924275817044],
       [0.21992529629742452, 'kanav', 0.821266189257077,
        0.6564407728304475, 0.14320684524513394],
       [0.2686789364833271, 0.18452722002562372, 0.23456589901633862,
        0.5724995162965943, 0.08135369133515458],
       [0.6027031421283714, 0.09202994550731547, 0.48407200423759367,
        0.5531526361165454, 0.05689689861552727],
       [0.1597152304131243, 0.8520796527577994, 0.8213607477546965,
        0.28479255409864257, 0.916858788987287],
       [0.06749600931555699, 0.5861002134711146, 0.557994098450656,
        0.4343721613922783, 0.15008446226327687],
       [0.6539937661594435, 0.9299043281493721, 0.9317830575366577,
        0.39305477936967514, 0.2079369884445076],
       [0.22497062484799124, 0.43054488504625854, 0.8432168127935649,
        0.7965914564489689, 0.9357133593737678],
       [0.06512636482725631, 0.9734775373851671, 0.13152905728253972,
        0.7188017731557145, 0.7441313458917175],
       [0.14688381372734793, 0.8905803167838822, 0.38964804846068213,
        0.4407711172388178, 0.09469990806284356],
       [0.9464559178959959, 0.3476488211858244, 0.8731190151024942,
        0.4687042904626155, 0.2247475379732201],
       [0.8736396592135223, 0.7113963488313334, 0.0022914821761400583,
        0.40765082848091994, 0.042966281555939845],
       [0.7106286826544861, 0.5226138696742261, 0.5027385422367144,
        0.965865748913141, 0.7790945997201331],
       [0.5657459322981103, 0.3916576553328116, 0.08573404461267675,
        0.512756074558626, 0.6931096068920942],
       [0.23804788397561416, 0.3259424118864196, 0.817357370477275,
        0.7609066044221627, 0.5186606969559883],
       [0.20978425175477633, 0.504296840357286, 0.861569564248992,
        0.1520208833374399, 0.9236824825615462],
       [0.42153178904854005, 0.1463244361346272, 0.808740195469414,
        0.9526560445887111, 0.8965064313268286],
       [0.04496947182458111, 0.9946730749629417, 0.2727767116094203,
        0.0501079322693615, 0.08898077605622134],
       [0.7056397211224181, 0.38993691160566635, 0.16452009515865162,
        0.870850707402535, 0.3070661472700763],
       [0.8682135145379903, 0.9806507257832185, 0.4521142938899646,
        0.09478103816515926, 0.17455524404522582],
       [0.6982598017727285, 0.7201604174383255, 0.644696120434663,
        0.18835452235933114, 0.13036062131106374],
       [0.4628775237871787, 0.03244081102172869, 0.15696998137371165,
        0.9230280534295283, 0.38478813414940294],
       [0.654035879437932, 0.922636875157039, 0.5420506962576565,
        0.8959284965471405, 0.05135005655359537],
       [0.06519265698763799, 0.05231077263784567, 0.06874320607336892,
        0.7468734269038833, 0.443335148641099],
       [0.6624514270732405, 0.6863600945512539, 0.4185965367636101,
        0.04862774042318807, 0.8980741801269468],
       [0.790025431811297, 0.11364866091710712, 0.16426526882451953,
        0.8878397618554772, 0.576013050904477],
       [0.6087016465016173, 0.7092869295402694, 0.8166812645522921,
        0.8826156427939379, 0.018044823956382405],
       [0.3382906205183305, 0.9538411920615014, 0.7643612624055738,
        0.4487569539111196, 0.25873749611932095],
       [0.5921885784434464, 0.8224077974844565, 0.08223059152573697,
        0.5826279470484622, 0.7485817188889937],
       [0.43893936788888743, 0.8569682436903083, 0.5351597024888336,
        0.12914592950334502, 0.03917442628688739],
       [0.8499438598416775, 0.8791985414498599, 0.09193179490094983,
        0.5273292928734742, 0.32625615470545577],
       [0.6946664264363703, 0.29221554548436424, 0.6817977335008624,
        0.10157742429216987, 0.9230716456597287],
       [0.9453290637841942, 0.9760455356841621, 0.04601857186560221,
        0.1584395252709433, 0.45374446870177276],
       [0.6677366765643736, 0.6397607475982298, 0.8445194318800882,
        0.46674729917569047, 0.10295588413244627],
       [0.6963563700423431, 0.06010179648619429, 0.4036477276669267,
        0.17127549952531917, 0.9828079272508256],
       [0.13156661843990858, 0.1994591443738426, 0.7543616245253985,
        0.657593563714239, 0.14967882595266746],
       [0.6480213015174201, 0.5606348065204697, 0.6464432836293563,
        0.36840574070252297, 0.17675257676985046],
       [0.7172380273465093, 0.919358380755276, 0.990939084706605,
        0.2488333017863641, 0.9472071868875247],
       [0.5381985666837831, 0.7350519522330508, 0.5664612898124514,
        0.7568175739232007, 0.0926336802759753],
       [0.6957650035794422, 0.40697732390285724, 0.33548988758840514,
        0.9261157578605519, 0.9876762385810613],
       [0.8778900486643579, 0.6536025078611317, 0.386444451548165,
        0.9974819683438222, 0.45887594639854923],
       [0.5611396305730633, 0.9863980125922592, 0.3921358331630106,
        0.10424655615927025, 0.932420760443912],
       [0.19185545188211894, 0.17971082600841837, 0.8547884772652645,
        0.6662658028872103, 0.6778186333143313],
       [0.2515189370523009, 0.9877055312200588, 0.08518694182624165,
        0.8106666288376551, 0.4639682155274265]], dtype=object)

In [23]:
newdata.columns

RangeIndex(start=0, stop=5, step=1)

In [24]:
newdata.T

,0,1,2,3,4,5,6,7,8,9,...,35,36,37,38,39,40,41,42,43,44
0,0.699851,0.684678,0.219925,0.268679,0.602703,0.159715,0.067496,0.653994,0.224971,0.065126,...,0.696356,0.131567,0.648021,0.717238,0.538199,0.695765,0.87789,0.56114,0.191855,0.251519
1,0.902919,0.500808,kanav,0.184527,0.09203,0.85208,0.5861,0.929904,0.430545,0.973478,...,0.060102,0.199459,0.560635,0.919358,0.735052,0.406977,0.653603,0.986398,0.179711,0.987706
2,0.206073,0.533985,0.821266,0.234566,0.484072,0.821361,0.557994,0.931783,0.843217,0.131529,...,0.403648,0.754362,0.646443,0.990939,0.566461,0.33549,0.386444,0.392136,0.854788,0.085187
3,0.554898,0.449384,0.656441,0.5725,0.553153,0.284793,0.434372,0.393055,0.796591,0.718802,...,0.171275,0.657594,0.368406,0.248833,0.756818,0.926116,0.997482,0.104247,0.666266,0.810667
4,0.151099,0.737692,0.143207,0.081354,0.056897,0.916859,0.150084,0.207937,0.935713,0.744131,...,0.982808,0.149679,0.176753,0.947207,0.092634,0.987676,0.458876,0.932421,0.677819,0.463968

In [25]:
newdata.sort_index(axis=0)

           0         1         2         3         4
0   0.699851  0.902919  0.206073  0.554898  0.151099
1   0.684678  0.500808  0.533985  0.449384  0.737692
2   0.219925     kanav  0.821266  0.656441  0.143207
3   0.268679  0.184527  0.234566  0.572500  0.081354
4   0.602703   0.09203  0.484072  0.553153  0.056897
5   0.159715   0.85208  0.821361  0.284793  0.916859
6   0.067496    0.5861  0.557994  0.434372  0.150084
7   0.653994  0.929904  0.931783  0.393055  0.207937
8   0.224971  0.430545  0.843217  0.796591  0.935713
9   0.065126  0.973478  0.131529  0.718802  0.744131
10  0.146884   0.89058  0.389648  0.440771  0.094700
11  0.946456  0.347649  0.873119  0.468704  0.224748
12  0.873640  0.711396  0.002291  0.407651  0.042966
13  0.710629  0.522614  0.502739  0.965866  0.779095
14  0.565746  0.391658  0.085734  0.512756  0.693110
15  0.238048  0.325942  0.817357  0.760907  0.518661
16  0.209784  0.504297  0.861570  0.152021  0.923682
17  0.421532  0.146324  0.808740  0.952656  0.896506
18  0.044969  0.994673  0.272777  0.050108  0.088981
19  0.705640  0.389937  0.164520  0.870851  0.307066
20  0.868214  0.980651  0.452114  0.094781  0.174555
21  0.698260   0.72016  0.644696  0.188355  0.130361
22  0.462878  0.032441  0.156970  0.923028  0.384788
23  0.654036  0.922637  0.542051  0.895928  0.051350
24  0.065193  0.052311  0.068743  0.746873  0.443335
25  0.662451   0.68636  0.418597  0.048628  0.898074
26  0.790025  0.113649  0.164265  0.887840  0.576013
27  0.608702  0.709287  0.816681  0.882616  0.018045
28  0.338291  0.953841  0.764361  0.448757  0.258737
29  0.592189  0.822408  0.082231  0.582628  0.748582
30  0.438939  0.856968  0.535160  0.129146  0.039174
31  0.849944  0.879199  0.091932  0.527329  0.326256
32  0.694666  0.292216  0.681798  0.101577  0.923072
33  0.945329  0.976046  0.046019  0.158440  0.453744
34  0.667737  0.639761  0.844519  0.466747  0.102956
35  0.696356  0.060102  0.403648  0.171275  0.982808
36  0.131567  0.199459  0.754362  0.657594  0.149679
37  0.648021  0.560635  0.646443  0.368406  0.176753
38  0.717238  0.919358  0.990939  0.248833  0.947207
39  0.538199  0.735052  0.566461  0.756818  0.092634
40  0.695765  0.406977  0.335490  0.926116  0.987676
41  0.877890  0.653603  0.386444  0.997482  0.458876
42  0.561140  0.986398  0.392136  0.104247  0.932421
43  0.191855  0.179711  0.854788  0.666266  0.677819
44  0.251519  0.987706  0.085187  0.810667  0.463968

In [26]:
newdata.sort_index(axis=1,ascending=False)

           4         3         2         1         0
0   0.151099  0.554898  0.206073  0.902919  0.699851
1   0.737692  0.449384  0.533985  0.500808  0.684678
2   0.143207  0.656441  0.821266     kanav  0.219925
3   0.081354  0.572500  0.234566  0.184527  0.268679
4   0.056897  0.553153  0.484072   0.09203  0.602703
5   0.916859  0.284793  0.821361   0.85208  0.159715
6   0.150084  0.434372  0.557994    0.5861  0.067496
7   0.207937  0.393055  0.931783  0.929904  0.653994
8   0.935713  0.796591  0.843217  0.430545  0.224971
9   0.744131  0.718802  0.131529  0.973478  0.065126
10  0.094700  0.440771  0.389648   0.89058  0.146884
11  0.224748  0.468704  0.873119  0.347649  0.946456
12  0.042966  0.407651  0.002291  0.711396  0.873640
13  0.779095  0.965866  0.502739  0.522614  0.710629
14  0.693110  0.512756  0.085734  0.391658  0.565746
15  0.518661  0.760907  0.817357  0.325942  0.238048
16  0.923682  0.152021  0.861570  0.504297  0.209784
17  0.896506  0.952656  0.808740  0.146324  0.421532
18  0.088981  0.050108  0.272777  0.994673  0.044969
19  0.307066  0.870851  0.164520  0.389937  0.705640
20  0.174555  0.094781  0.452114  0.980651  0.868214
21  0.130361  0.188355  0.644696   0.72016  0.698260
22  0.384788  0.923028  0.156970  0.032441  0.462878
23  0.051350  0.895928  0.542051  0.922637  0.654036
24  0.443335  0.746873  0.068743  0.052311  0.065193
25  0.898074  0.048628  0.418597   0.68636  0.662451
26  0.576013  0.887840  0.164265  0.113649  0.790025
27  0.018045  0.882616  0.816681  0.709287  0.608702
28  0.258737  0.448757  0.764361  0.953841  0.338291
29  0.748582  0.582628  0.082231  0.822408  0.592189
30  0.039174  0.129146  0.535160  0.856968  0.438939
31  0.326256  0.527329  0.091932  0.879199  0.849944
32  0.923072  0.101577  0.681798  0.292216  0.694666
33  0.453744  0.158440  0.046019  0.976046  0.945329
34  0.102956  0.466747  0.844519  0.639761  0.667737
35  0.982808  0.171275  0.403648  0.060102  0.696356
36  0.149679  0.657594  0.754362  0.199459  0.131567
37  0.176753  0.368406  0.646443  0.560635  0.648021
38  0.947207  0.248833  0.990939  0.919358  0.717238
39  0.092634  0.756818  0.566461  0.735052  0.538199
40  0.987676  0.926116  0.335490  0.406977  0.695765
41  0.458876  0.997482  0.386444  0.653603  0.877890
42  0.932421  0.104247  0.392136  0.986398  0.561140
43  0.677819  0.666266  0.854788  0.179711  0.191855
44  0.463968  0.810667  0.085187  0.987706  0.251519

In [27]:
newdata[0]

0     0.699851
1     0.684678
2     0.219925
3     0.268679
4     0.602703
5     0.159715
6     0.067496
7     0.653994
8     0.224971
9     0.065126
10    0.146884
11    0.946456
12    0.873640
13    0.710629
14    0.565746
15    0.238048
16    0.209784
17    0.421532
18    0.044969
19    0.705640
20    0.868214
21    0.698260
22    0.462878
23    0.654036
24    0.065193
25    0.662451
26    0.790025
27    0.608702
28    0.338291
29    0.592189
30    0.438939
31    0.849944
32    0.694666
33    0.945329
34    0.667737
35    0.696356
36    0.131567
37    0.648021
38    0.717238
39    0.538199
40    0.695765
41    0.877890
42    0.561140
43    0.191855
44    0.251519
Name: 0, dtype: float64

In [28]:
type(newdata[0])

pandas.core.series.Series

In [29]:
newdata.columns=list("ABCDE")

In [30]:
newdata

           A         B         C         D         E
0   0.699851  0.902919  0.206073  0.554898  0.151099
1   0.684678  0.500808  0.533985  0.449384  0.737692
2   0.219925     kanav  0.821266  0.656441  0.143207
3   0.268679  0.184527  0.234566  0.572500  0.081354
4   0.602703   0.09203  0.484072  0.553153  0.056897
5   0.159715   0.85208  0.821361  0.284793  0.916859
6   0.067496    0.5861  0.557994  0.434372  0.150084
7   0.653994  0.929904  0.931783  0.393055  0.207937
8   0.224971  0.430545  0.843217  0.796591  0.935713
9   0.065126  0.973478  0.131529  0.718802  0.744131
10  0.146884   0.89058  0.389648  0.440771  0.094700
11  0.946456  0.347649  0.873119  0.468704  0.224748
12  0.873640  0.711396  0.002291  0.407651  0.042966
13  0.710629  0.522614  0.502739  0.965866  0.779095
14  0.565746  0.391658  0.085734  0.512756  0.693110
15  0.238048  0.325942  0.817357  0.760907  0.518661
16  0.209784  0.504297  0.861570  0.152021  0.923682
17  0.421532  0.146324  0.808740  0.952656  0.896506
18  0.044969  0.994673  0.272777  0.050108  0.088981
19  0.705640  0.389937  0.164520  0.870851  0.307066
20  0.868214  0.980651  0.452114  0.094781  0.174555
21  0.698260   0.72016  0.644696  0.188355  0.130361
22  0.462878  0.032441  0.156970  0.923028  0.384788
23  0.654036  0.922637  0.542051  0.895928  0.051350
24  0.065193  0.052311  0.068743  0.746873  0.443335
25  0.662451   0.68636  0.418597  0.048628  0.898074
26  0.790025  0.113649  0.164265  0.887840  0.576013
27  0.608702  0.709287  0.816681  0.882616  0.018045
28  0.338291  0.953841  0.764361  0.448757  0.258737
29  0.592189  0.822408  0.082231  0.582628  0.748582
30  0.438939  0.856968  0.535160  0.129146  0.039174
31  0.849944  0.879199  0.091932  0.527329  0.326256
32  0.694666  0.292216  0.681798  0.101577  0.923072
33  0.945329  0.976046  0.046019  0.158440  0.453744
34  0.667737  0.639761  0.844519  0.466747  0.102956
35  0.696356  0.060102  0.403648  0.171275  0.982808
36  0.131567  0.199459  0.754362  0.657594  0.149679
37  0.648021  0.560635  0.646443  0.368406  0.176753
38  0.717238  0.919358  0.990939  0.248833  0.947207
39  0.538199  0.735052  0.566461  0.756818  0.092634
40  0.695765  0.406977  0.335490  0.926116  0.987676
41  0.877890  0.653603  0.386444  0.997482  0.458876
42  0.561140  0.986398  0.392136  0.104247  0.932421
43  0.191855  0.179711  0.854788  0.666266  0.677819
44  0.251519  0.987706  0.085187  0.810667  0.463968

In [31]:
newdata.loc[[1,3],:]

          A         B         C         D         E
1  0.684678  0.500808  0.533985  0.449384  0.737692
3  0.268679  0.184527  0.234566  0.572500  0.081354

In [32]:
newdata.loc[(newdata['A']<0.4)|(newdata['C']>0.2)]

           A         B         C         D         E
0   0.699851  0.902919  0.206073  0.554898  0.151099
1   0.684678  0.500808  0.533985  0.449384  0.737692
2   0.219925     kanav  0.821266  0.656441  0.143207
3   0.268679  0.184527  0.234566  0.572500  0.081354
4   0.602703   0.09203  0.484072  0.553153  0.056897
5   0.159715   0.85208  0.821361  0.284793  0.916859
6   0.067496    0.5861  0.557994  0.434372  0.150084
7   0.653994  0.929904  0.931783  0.393055  0.207937
8   0.224971  0.430545  0.843217  0.796591  0.935713
9   0.065126  0.973478  0.131529  0.718802  0.744131
10  0.146884   0.89058  0.389648  0.440771  0.094700
11  0.946456  0.347649  0.873119  0.468704  0.224748
13  0.710629  0.522614  0.502739  0.965866  0.779095
15  0.238048  0.325942  0.817357  0.760907  0.518661
16  0.209784  0.504297  0.861570  0.152021  0.923682
17  0.421532  0.146324  0.808740  0.952656  0.896506
18  0.044969  0.994673  0.272777  0.050108  0.088981
20  0.868214  0.980651  0.452114  0.094781  0.174555
21  0.698260   0.72016  0.644696  0.188355  0.130361
23  0.654036  0.922637  0.542051  0.895928  0.051350
24  0.065193  0.052311  0.068743  0.746873  0.443335
25  0.662451   0.68636  0.418597  0.048628  0.898074
27  0.608702  0.709287  0.816681  0.882616  0.018045
28  0.338291  0.953841  0.764361  0.448757  0.258737
30  0.438939  0.856968  0.535160  0.129146  0.039174
32  0.694666  0.292216  0.681798  0.101577  0.923072
34  0.667737  0.639761  0.844519  0.466747  0.102956
35  0.696356  0.060102  0.403648  0.171275  0.982808
36  0.131567  0.199459  0.754362  0.657594  0.149679
37  0.648021  0.560635  0.646443  0.368406  0.176753
38  0.717238  0.919358  0.990939  0.248833  0.947207
39  0.538199  0.735052  0.566461  0.756818  0.092634
40  0.695765  0.406977  0.335490  0.926116  0.987676
41  0.877890  0.653603  0.386444  0.997482  0.458876
42  0.561140  0.986398  0.392136  0.104247  0.932421
43  0.191855  0.179711  0.854788  0.666266  0.677819
44  0.251519  0.987706  0.085187  0.810667  0.463968

In [33]:
newdata.iloc[0,3]

0.5548982693863784

In [34]:
newdata.drop(['A'],axis=1)

           B         C         D         E
0   0.902919  0.206073  0.554898  0.151099
1   0.500808  0.533985  0.449384  0.737692
2      kanav  0.821266  0.656441  0.143207
3   0.184527  0.234566  0.572500  0.081354
4    0.09203  0.484072  0.553153  0.056897
5    0.85208  0.821361  0.284793  0.916859
6     0.5861  0.557994  0.434372  0.150084
7   0.929904  0.931783  0.393055  0.207937
8   0.430545  0.843217  0.796591  0.935713
9   0.973478  0.131529  0.718802  0.744131
10   0.89058  0.389648  0.440771  0.094700
11  0.347649  0.873119  0.468704  0.224748
12  0.711396  0.002291  0.407651  0.042966
13  0.522614  0.502739  0.965866  0.779095
14  0.391658  0.085734  0.512756  0.693110
15  0.325942  0.817357  0.760907  0.518661
16  0.504297  0.861570  0.152021  0.923682
17  0.146324  0.808740  0.952656  0.896506
18  0.994673  0.272777  0.050108  0.088981
19  0.389937  0.164520  0.870851  0.307066
20  0.980651  0.452114  0.094781  0.174555
21   0.72016  0.644696  0.188355  0.130361
22  0.032441  0.156970  0.923028  0.384788
23  0.922637  0.542051  0.895928  0.051350
24  0.052311  0.068743  0.746873  0.443335
25   0.68636  0.418597  0.048628  0.898074
26  0.113649  0.164265  0.887840  0.576013
27  0.709287  0.816681  0.882616  0.018045
28  0.953841  0.764361  0.448757  0.258737
29  0.822408  0.082231  0.582628  0.748582
30  0.856968  0.535160  0.129146  0.039174
31  0.879199  0.091932  0.527329  0.326256
32  0.292216  0.681798  0.101577  0.923072
33  0.976046  0.046019  0.158440  0.453744
34  0.639761  0.844519  0.466747  0.102956
35  0.060102  0.403648  0.171275  0.982808
36  0.199459  0.754362  0.657594  0.149679
37  0.560635  0.646443  0.368406  0.176753
38  0.919358  0.990939  0.248833  0.947207
39  0.735052  0.566461  0.756818  0.092634
40  0.406977  0.335490  0.926116  0.987676
41  0.653603  0.386444  0.997482  0.458876
42  0.986398  0.392136  0.104247  0.932421
43  0.179711  0.854788  0.666266  0.677819
44  0.987706  0.085187  0.810667  0.463968

In [35]:
newdata.reset_index(drop=True)

           A         B         C         D         E
0   0.699851  0.902919  0.206073  0.554898  0.151099
1   0.684678  0.500808  0.533985  0.449384  0.737692
2   0.219925     kanav  0.821266  0.656441  0.143207
3   0.268679  0.184527  0.234566  0.572500  0.081354
4   0.602703   0.09203  0.484072  0.553153  0.056897
5   0.159715   0.85208  0.821361  0.284793  0.916859
6   0.067496    0.5861  0.557994  0.434372  0.150084
7   0.653994  0.929904  0.931783  0.393055  0.207937
8   0.224971  0.430545  0.843217  0.796591  0.935713
9   0.065126  0.973478  0.131529  0.718802  0.744131
10  0.146884   0.89058  0.389648  0.440771  0.094700
11  0.946456  0.347649  0.873119  0.468704  0.224748
12  0.873640  0.711396  0.002291  0.407651  0.042966
13  0.710629  0.522614  0.502739  0.965866  0.779095
14  0.565746  0.391658  0.085734  0.512756  0.693110
15  0.238048  0.325942  0.817357  0.760907  0.518661
16  0.209784  0.504297  0.861570  0.152021  0.923682
17  0.421532  0.146324  0.808740  0.952656  0.896506
18  0.044969  0.994673  0.272777  0.050108  0.088981
19  0.705640  0.389937  0.164520  0.870851  0.307066
20  0.868214  0.980651  0.452114  0.094781  0.174555
21  0.698260   0.72016  0.644696  0.188355  0.130361
22  0.462878  0.032441  0.156970  0.923028  0.384788
23  0.654036  0.922637  0.542051  0.895928  0.051350
24  0.065193  0.052311  0.068743  0.746873  0.443335
25  0.662451   0.68636  0.418597  0.048628  0.898074
26  0.790025  0.113649  0.164265  0.887840  0.576013
27  0.608702  0.709287  0.816681  0.882616  0.018045
28  0.338291  0.953841  0.764361  0.448757  0.258737
29  0.592189  0.822408  0.082231  0.582628  0.748582
30  0.438939  0.856968  0.535160  0.129146  0.039174
31  0.849944  0.879199  0.091932  0.527329  0.326256
32  0.694666  0.292216  0.681798  0.101577  0.923072
33  0.945329  0.976046  0.046019  0.158440  0.453744
34  0.667737  0.639761  0.844519  0.466747  0.102956
35  0.696356  0.060102  0.403648  0.171275  0.982808
36  0.131567  0.199459  0.754362  0.657594  0.149679
37  0.648021  0.560635  0.646443  0.368406  0.176753
38  0.717238  0.919358  0.990939  0.248833  0.947207
39  0.538199  0.735052  0.566461  0.756818  0.092634
40  0.695765  0.406977  0.335490  0.926116  0.987676
41  0.877890  0.653603  0.386444  0.997482  0.458876
42  0.561140  0.986398  0.392136  0.104247  0.932421
43  0.191855  0.179711  0.854788  0.666266  0.677819
44  0.251519  0.987706  0.085187  0.810667  0.463968

In [36]:
newdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       45 non-null     float64
 1   B       45 non-null     object
 2   C       45 non-null     float64
 3   D       45 non-null     float64
 4   E       45 non-null     float64
dtypes: float64(4), object(1)
memory usage: 1.9+ KB

In [39]:
exc=pd.read_excel('student.xlrd')

FileNotFoundError: [Errno 2] No such file or directory: 'student.xlrd'